version: "3.9"

services:
  app:
    image: ${application_image_name}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    command: python src/main.py
    depends_on:
      - db
    networks:
      - parser_application

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${user}
      MONGO_INITDB_ROOT_PASSWORD: ${password}
    container_name: ${database_name}
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - parser_application

volumes:
  mongodb:

networks:
  parser_application:
    driver: bridge