version: "3.9"

services:
  app:
    image: app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    command: python src/main.py
    depends_on:
      - db
    
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${user}
      MONGO_INITDB_ROOT_PASSWORD: ${password}
    container_name: ${database_name}
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb:
