version: "3.9"

services:
  app:
    image: ${application_image_name}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    depends_on:
      - postgres

  metabase:
      image: metabase/metabase
      ports:
        - 3000:3000
      environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: ${database_name}
        MB_DB_PORT: 5432
        MB_DB_USER: ${user}
        MB_DB_PASS: ${password}
        MB_DB_HOST: ${host}
      depends_on:
        - postgres
      links:
        - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      METABASE_PASSWORD: ${password}
    volumes:
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb: