version: "3.9"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${user}
      MONGO_INITDB_ROOT_PASSWORD: ${password}
    container_name: ${database_name}
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb:
